let n ="                 ＲＥＰＯＲＴＣＡＲＤ                        "
console.log(n)

let a = "𝐍 𝐀 𝐌 𝐄 - 𝐑 𝐎 𝐇 𝐈 𝐓"
console.log(a)


let b ="ＳＣＨＯＯＬ -​​​​​ 𝐃.𝐀.𝐕"
console.log(b)



let x ="ＳＥＣＴＩＯＮ - 𝙱 "
console.log(x)


let y ="ＲＯＬＬ ＮＯ － ２１"
console.log(y)


let z = "                 ＊＊𝗠𝗔𝗥𝗞𝗦 𝗦𝗖𝗢𝗥𝗘𝗗 >>                "
console.log(z)

let p =  "  𝟏. 𝔼ℕ𝔾𝕃𝕀𝕊ℍ-𝟡𝟘/𝟙𝟘𝟘    "
console.log(p)

let L =  "  𝟚. 𝕄𝔸𝕋ℍ𝔼𝕄𝔸𝕋𝕀ℂ𝕊 - 𝟠𝟠/𝟙𝟘𝟘                    "
console.log(L)

let k = "  𝟛.  𝕊ℂ𝕀𝔼ℕℂ𝔼 - 𝟡𝟙/𝟙𝟘𝟘                          "
console.log(k)

let g = "     ＴＯＴＡＬ － ２６９／３００       "
console.log (g)


let c =  "          ＧＲＡＤＥ－Ａ (^_^)           "
console.log(c)


let q = "                     🇶​​​​​ 🇺 ​​​​​🇦​​​​​ 🇱 ​​​​​🇮 ​​​​​🇫 ​​​​​🇮 ​​​​​🇪 ​​​​​🇩​​​​​                              "
console.log(q) 